var data = '{'
+ ' "name" : "/Users/obzota/Files",'
+ ' "shortname" : "Files",'
+ ' "depth" : "0",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/.DS_Store",'
+ ' "size" : "8196"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/.localized",'
+ ' "size" : "0"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photo on 11-8-15 at 1.42 PM #2.jpeg",'
+ ' "size" : "107530"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' {'
+ ' "name" : "/Users/obzota/Files/Documents",'
+ ' "shortname" : "Documents",'
+ ' "depth" : "1",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Documents/.DS_Store",'
+ ' "size" : "6148"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Documents/.localized",'
+ ' "size" : "0"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Documents/About Stacks.pdf",'
+ ' "size" : "466028"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Documents/test.JSON",'
+ ' "size" : "0"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' {'
+ ' "name" : "/Users/obzota/Files/Documents/drwho",'
+ ' "shortname" : "drwho",'
+ ' "depth" : "2",'
+ ' "Files" : ['
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Documents/ufrgs",'
+ ' "shortname" : "ufrgs",'
+ ' "depth" : "2",'
+ ' "Files" : ['
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/iChat Icons",'
+ ' "shortname" : "iChat Icons",'
+ ' "depth" : "1",'
+ ' "Files" : ['
+ ' ],'
+ ' "Folders" : ['
+ ' {'
+ ' "name" : "/Users/obzota/Files/iChat Icons/Flags",'
+ ' "shortname" : "Flags",'
+ ' "depth" : "2",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Argentina.png",'
+ ' "size" : "42260"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Australia.png",'
+ ' "size" : "30993"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Austria.png",'
+ ' "size" : "29129"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Belgium.png",'
+ ' "size" : "28228"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Brazil.png",'
+ ' "size" : "47060"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Cameroon.png",'
+ ' "size" : "33782"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Canada.png",'
+ ' "size" : "29471"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Chile.png",'
+ ' "size" : "29610"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/China.png",'
+ ' "size" : "36475"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Denmark.png",'
+ ' "size" : "29598"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Finland.png",'
+ ' "size" : "28265"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/France.png",'
+ ' "size" : "30193"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Germany.png",'
+ ' "size" : "24658"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Greece.png",'
+ ' "size" : "25662"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Hong Kong.png",'
+ ' "size" : "44405"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Hungary.png",'
+ ' "size" : "26630"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Iceland.png",'
+ ' "size" : "30164"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/India.png",'
+ ' "size" : "42542"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Indonesia.png",'
+ ' "size" : "27923"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Ireland.png",'
+ ' "size" : "31153"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Israel.png",'
+ ' "size" : "32311"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Italy.png",'
+ ' "size" : "29722"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Japan.png",'
+ ' "size" : "29853"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Malaysia.png",'
+ ' "size" : "36872"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Mexico.png",'
+ ' "size" : "40086"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Netherlands.png",'
+ ' "size" : "27048"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/New Zealand.png",'
+ ' "size" : "30996"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Norway.png",'
+ ' "size" : "32384"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Pakistan.png",'
+ ' "size" : "30099"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Palestine.png",'
+ ' "size" : "26992"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Peru.png",'
+ ' "size" : "28276"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Poland.png",'
+ ' "size" : "29542"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Portugal.png",'
+ ' "size" : "54636"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Puerto Rico.png",'
+ ' "size" : "34622"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Romania.png",'
+ ' "size" : "31282"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Russia.png",'
+ ' "size" : "25259"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Saudi Arabia.png",'
+ ' "size" : "52261"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Singapore.png",'
+ ' "size" : "34695"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/South Africa.png",'
+ ' "size" : "36197"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/South Korea.png",'
+ ' "size" : "39398"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Spain.png",'
+ ' "size" : "40429"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Sweden.png",'
+ ' "size" : "31115"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Switzerland.png",'
+ ' "size" : "26169"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Thailand.png",'
+ ' "size" : "26244"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Turkey.png",'
+ ' "size" : "34444"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/UK.png",'
+ ' "size" : "34461"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Ukraine.png",'
+ ' "size" : "30937"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Uruguay.png",'
+ ' "size" : "40083"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flags/Venezuela.png",'
+ ' "size" : "38279"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/iChat Icons/Flowers",'
+ ' "shortname" : "Flowers",'
+ ' "depth" : "2",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flowers/African Daisy.gif",'
+ ' "size" : "2624"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flowers/Dandelion.gif",'
+ ' "size" : "2728"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flowers/Ixia.gif",'
+ ' "size" : "2613"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Flowers/Sunflower.gif",'
+ ' "size" : "2730"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/iChat Icons/Fruit",'
+ ' "shortname" : "Fruit",'
+ ' "depth" : "2",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Fruit/Green Apple.gif",'
+ ' "size" : "2159"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Fruit/Orange.gif",'
+ ' "size" : "2647"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Fruit/Pear.gif",'
+ ' "size" : "1748"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Fruit/Strawberry.gif",'
+ ' "size" : "1947"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/iChat Icons/Funk Animals",'
+ ' "shortname" : "Funk Animals",'
+ ' "depth" : "2",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Funk Animals/Bluehound.gif",'
+ ' "size" : "1968"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Funk Animals/Doggie.gif",'
+ ' "size" : "2038"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Funk Animals/Pointy.gif",'
+ ' "size" : "1954"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Funk Animals/PurpGuy.gif",'
+ ' "size" : "1839"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Funk Animals/Woof.gif",'
+ ' "size" : "1820"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/iChat Icons/Gems",'
+ ' "shortname" : "Gems",'
+ ' "depth" : "2",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Gems/Diamond Heart.gif",'
+ ' "size" : "2836"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Gems/Diamond Round.gif",'
+ ' "size" : "2793"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Gems/Diamond Square.gif",'
+ ' "size" : "2204"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Gems/Emerald Round.gif",'
+ ' "size" : "2789"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Gems/Emerald Square.gif",'
+ ' "size" : "2205"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Gems/Princess Heart.gif",'
+ ' "size" : "2785"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Gems/Princess Round.gif",'
+ ' "size" : "2792"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Gems/Princess Square.gif",'
+ ' "size" : "2200"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Gems/Ruby Heart.gif",'
+ ' "size" : "2781"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Gems/Ruby Round.gif",'
+ ' "size" : "2734"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Gems/Ruby Square.gif",'
+ ' "size" : "2208"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Gems/Sapphire Square.gif",'
+ ' "size" : "2187"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/iChat Icons/Hollowbody Guitars",'
+ ' "shortname" : "Hollowbody Guitars",'
+ ' "depth" : "2",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Hollowbody Guitars/Hollowbody 1.gif",'
+ ' "size" : "2078"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Hollowbody Guitars/Hollowbody 2.gif",'
+ ' "size" : "2081"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Hollowbody Guitars/Hollowbody 3.gif",'
+ ' "size" : "2159"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Hollowbody Guitars/Hollowbody 4.gif",'
+ ' "size" : "2094"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Hollowbody Guitars/Hollowbody 6.gif",'
+ ' "size" : "2148"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/iChat Icons/Planets",'
+ ' "shortname" : "Planets",'
+ ' "depth" : "2",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Planets/Earth (Americas).gif",'
+ ' "size" : "2454"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Planets/Earth (Australasia).gif",'
+ ' "size" : "2490"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Planets/Earth (Clouds).gif",'
+ ' "size" : "2760"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Planets/Earth and Moon.gif",'
+ ' "size" : "1988"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Planets/Extrasolar Giant.gif",'
+ ' "size" : "2340"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Planets/Jupiter.gif",'
+ ' "size" : "2610"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Planets/Mars.gif",'
+ ' "size" : "2280"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Planets/Mercury.gif",'
+ ' "size" : "2580"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Planets/Neptune.gif",'
+ ' "size" : "2204"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Planets/Pluto and Charon.gif",'
+ ' "size" : "1724"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Planets/Saturn.gif",'
+ ' "size" : "2547"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Planets/Venus.gif",'
+ ' "size" : "2150"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/iChat Icons/Tribal Masks",'
+ ' "shortname" : "Tribal Masks",'
+ ' "depth" : "2",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Tribal Masks/B\'galla Mask.gif",'
+ ' "size" : "2505"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Tribal Masks/Bauchi Mask.gif",'
+ ' "size" : "2356"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Tribal Masks/Baule Mask.gif",'
+ ' "size" : "2496"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Tribal Masks/Eket Mask.gif",'
+ ' "size" : "2978"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Tribal Masks/Gere Mask.gif",'
+ ' "size" : "2556"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Tribal Masks/Makonde Mask.gif",'
+ ' "size" : "2678"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Tribal Masks/Raratonga Mask.gif",'
+ ' "size" : "2881"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Tribal Masks/Rukai Mask.gif",'
+ ' "size" : "2881"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/iChat Icons/Tribal Masks/Yoruba Mask.gif",'
+ ' "size" : "2424"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Movies",'
+ ' "shortname" : "Movies",'
+ ' "depth" : "1",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Movies/.localized",'
+ ' "size" : "0"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Music",'
+ ' "shortname" : "Music",'
+ ' "depth" : "1",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Music/.localized",'
+ ' "size" : "0"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' {'
+ ' "name" : "/Users/obzota/Files/Music/iTunes",'
+ ' "shortname" : "iTunes",'
+ ' "depth" : "2",'
+ ' "Files" : ['
+ ' ],'
+ ' "Folders" : ['
+ ' {'
+ ' "name" : "/Users/obzota/Files/Music/iTunes/Album Artwork",'
+ ' "shortname" : "Album Artwork",'
+ ' "depth" : "3",'
+ ' "Files" : ['
+ ' ],'
+ ' "Folders" : ['
+ ' {'
+ ' "name" : "/Users/obzota/Files/Music/iTunes/Album Artwork/Cache",'
+ ' "shortname" : "Cache",'
+ ' "depth" : "4",'
+ ' "Files" : ['
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Music/iTunes/Album Artwork/Download",'
+ ' "shortname" : "Download",'
+ ' "depth" : "4",'
+ ' "Files" : ['
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ]'
+ ' }'
+ ' ]'
+ ' }'
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photo Booth Library",'
+ ' "shortname" : "Photo Booth Library",'
+ ' "depth" : "1",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photo Booth Library/Recents.plist",'
+ ' "size" : "396"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photo Booth Library/Backdrops",'
+ ' "shortname" : "Backdrops",'
+ ' "depth" : "2",'
+ ' "Files" : ['
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photo Booth Library/Contents",'
+ ' "shortname" : "Contents",'
+ ' "depth" : "2",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photo Booth Library/Contents/PkgInfo",'
+ ' "size" : "8"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photo Booth Library/Originals",'
+ ' "shortname" : "Originals",'
+ ' "depth" : "2",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photo Booth Library/Originals/Photo on 11-8-15 at 1.41 PM (original).jpg",'
+ ' "size" : "121751"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photo Booth Library/Originals/Photo on 11-8-15 at 1.42 PM #2 (original).jpg",'
+ ' "size" : "120005"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photo Booth Library/Originals/Photo on 11-8-15 at 1.42 PM (original).jpg",'
+ ' "size" : "105235"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photo Booth Library/Pictures",'
+ ' "shortname" : "Pictures",'
+ ' "depth" : "2",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photo Booth Library/Pictures/Photo on 11-8-15 at 1.41 PM.jpg",'
+ ' "size" : "106779"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photo Booth Library/Pictures/Photo on 11-8-15 at 1.42 PM #2.jpg",'
+ ' "size" : "105228"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photo Booth Library/Pictures/Photo on 11-8-15 at 1.42 PM.jpg",'
+ ' "size" : "94210"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary",'
+ ' "shortname" : "Photos Library.photoslibrary",'
+ ' "depth" : "1",'
+ ' "Files" : ['
+ ' ],'
+ ' "Folders" : ['
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/Attachments",'
+ ' "shortname" : "Attachments",'
+ ' "depth" : "2",'
+ ' "Files" : ['
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/database",'
+ ' "shortname" : "database",'
+ ' "depth" : "2",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/database/DataModelVersion.plist",'
+ ' "size" : "458"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/database/ImageProxies.apdb",'
+ ' "size" : "638976"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/database/ImageProxies.apdb-wal",'
+ ' "size" : "0"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/database/Library.apdb",'
+ ' "size" : "3325952"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/database/Library.apdb-wal",'
+ ' "size" : "0"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/database/metaSchema.db",'
+ ' "size" : "278528"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/database/metaSchema.db-wal",'
+ ' "size" : "0"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/database/Person.db",'
+ ' "size" : "655360"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/database/Person.db-wal",'
+ ' "size" : "0"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/database/Properties.apdb",'
+ ' "size" : "229376"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/database/Properties.apdb-wal",'
+ ' "size" : "0"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/database/RKVersion_searchIndexText.skindex",'
+ ' "size" : "6144"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/Masks",'
+ ' "shortname" : "Masks",'
+ ' "depth" : "2",'
+ ' "Files" : ['
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/Masters",'
+ ' "shortname" : "Masters",'
+ ' "depth" : "2",'
+ ' "Files" : ['
+ ' ],'
+ ' "Folders" : ['
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/Masters/2015",'
+ ' "shortname" : "2015",'
+ ' "depth" : "3",'
+ ' "Files" : ['
+ ' ],'
+ ' "Folders" : ['
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/Masters/2015/11",'
+ ' "shortname" : "11",'
+ ' "depth" : "4",'
+ ' "Files" : ['
+ ' ],'
+ ' "Folders" : ['
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/Masters/2015/11/08",'
+ ' "shortname" : "08",'
+ ' "depth" : "5",'
+ ' "Files" : ['
+ ' ],'
+ ' "Folders" : ['
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/Masters/2015/11/08/20151108-154737",'
+ ' "shortname" : "20151108-154737",'
+ ' "depth" : "6",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/Masters/2015/11/08/20151108-154737/Photo on 11-8-15 at 1.42 PM #2.jpeg",'
+ ' "size" : "107530"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ]'
+ ' }'
+ ' ]'
+ ' }'
+ ' ]'
+ ' }'
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/Plugins",'
+ ' "shortname" : "Plugins",'
+ ' "depth" : "2",'
+ ' "Files" : ['
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/Previews",'
+ ' "shortname" : "Previews",'
+ ' "depth" : "2",'
+ ' "Files" : ['
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/private",'
+ ' "shortname" : "private",'
+ ' "depth" : "2",'
+ ' "Files" : ['
+ ' ],'
+ ' "Folders" : ['
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/private/com.apple.cloudphotosd",'
+ ' "shortname" : "com.apple.cloudphotosd",'
+ ' "depth" : "3",'
+ ' "Files" : ['
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/private/com.apple.MediaLibraryService",'
+ ' "shortname" : "com.apple.MediaLibraryService",'
+ ' "depth" : "3",'
+ ' "Files" : ['
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/private/com.apple.photomodel",'
+ ' "shortname" : "com.apple.photomodel",'
+ ' "depth" : "3",'
+ ' "Files" : ['
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/private/com.apple.photomoments",'
+ ' "shortname" : "com.apple.photomoments",'
+ ' "depth" : "3",'
+ ' "Files" : ['
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/private/com.apple.Photos",'
+ ' "shortname" : "com.apple.Photos",'
+ ' "depth" : "3",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/private/com.apple.Photos/appPrivateData.plist",'
+ ' "size" : "521"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/private/com.apple.Photos/faces",'
+ ' "shortname" : "faces",'
+ ' "depth" : "4",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/private/com.apple.Photos/faces/sync-marker.plist",'
+ ' "size" : "382"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ]'
+ ' }'
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/resources",'
+ ' "shortname" : "resources",'
+ ' "depth" : "2",'
+ ' "Files" : ['
+ ' ],'
+ ' "Folders" : ['
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/modelresources",'
+ ' "shortname" : "modelresources",'
+ ' "depth" : "3",'
+ ' "Files" : ['
+ ' ],'
+ ' "Folders" : ['
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/modelresources/106",'
+ ' "shortname" : "106",'
+ ' "depth" : "4",'
+ ' "Files" : ['
+ ' ],'
+ ' "Folders" : ['
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/modelresources/106/79",'
+ ' "shortname" : "79",'
+ ' "depth" : "5",'
+ ' "Files" : ['
+ ' ],'
+ ' "Folders" : ['
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/modelresources/106/79/jOrtdII6R8m%owrJdNg1Iw",'
+ ' "shortname" : "jOrtdII6R8m%owrJdNg1Iw",'
+ ' "depth" : "6",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/modelresources/106/79/jOrtdII6R8m%owrJdNg1Iw/Photo on 11-8-15 at 1.42 PM #2.jpg",'
+ ' "size" : "109571"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ]'
+ ' }'
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/modelresources/113",'
+ ' "shortname" : "113",'
+ ' "depth" : "4",'
+ ' "Files" : ['
+ ' ],'
+ ' "Folders" : ['
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/modelresources/113/88",'
+ ' "shortname" : "88",'
+ ' "depth" : "5",'
+ ' "Files" : ['
+ ' ],'
+ ' "Folders" : ['
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/modelresources/113/88/qXkxpJf5QJCXX+55HPOjKg",'
+ ' "shortname" : "qXkxpJf5QJCXX+55HPOjKg",'
+ ' "depth" : "6",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/modelresources/113/88/qXkxpJf5QJCXX+55HPOjKg/Photo on 11-8-15 at 1.42 PM #2.jpg",'
+ ' "size" : "28370"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ]'
+ ' }'
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/modelresources/79",'
+ ' "shortname" : "79",'
+ ' "depth" : "4",'
+ ' "Files" : ['
+ ' ],'
+ ' "Folders" : ['
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/modelresources/79/74",'
+ ' "shortname" : "74",'
+ ' "depth" : "5",'
+ ' "Files" : ['
+ ' ],'
+ ' "Folders" : ['
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/modelresources/79/74/OJtSz1EJQ0SIvV+QRs7IsA",'
+ ' "shortname" : "OJtSz1EJQ0SIvV+QRs7IsA",'
+ ' "depth" : "6",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/modelresources/79/74/OJtSz1EJQ0SIvV+QRs7IsA/Photo on 11-8-15 at 1.42 PM #2.jpg",'
+ ' "size" : "33692"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ]'
+ ' }'
+ ' ]'
+ ' }'
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/moments",'
+ ' "shortname" : "moments",'
+ ' "depth" : "3",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/moments/analysismetadata.plist",'
+ ' "size" : "535"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/moments/historicalmarker.plist",'
+ ' "size" : "382"'
+ ' },'
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/moments/serverinfo.plist",'
+ ' "size" : "1110"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/projects",'
+ ' "shortname" : "projects",'
+ ' "depth" : "3",'
+ ' "Files" : ['
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/recovery",'
+ ' "shortname" : "recovery",'
+ ' "depth" : "3",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/recovery/Info.plist",'
+ ' "size" : "427"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/recovery/RKAdjustmentData",'
+ ' "shortname" : "RKAdjustmentData",'
+ ' "depth" : "4",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/recovery/RKAdjustmentData/0000000000.lij",'
+ ' "size" : "1737"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/recovery/RKAdminData",'
+ ' "shortname" : "RKAdminData",'
+ ' "depth" : "4",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/recovery/RKAdminData/0000000000.lij",'
+ ' "size" : "234"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/recovery/RKAlbum",'
+ ' "shortname" : "RKAlbum",'
+ ' "depth" : "4",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/recovery/RKAlbum/0000000000.lij",'
+ ' "size" : "18970"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/recovery/RKAlbumVersion",'
+ ' "shortname" : "RKAlbumVersion",'
+ ' "depth" : "4",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/recovery/RKAlbumVersion/0000000000.lij",'
+ ' "size" : "232"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/recovery/RKCustomSortOrder",'
+ ' "shortname" : "RKCustomSortOrder",'
+ ' "depth" : "4",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/recovery/RKCustomSortOrder/0000000000.lij",'
+ ' "size" : "805"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/recovery/RKFace",'
+ ' "shortname" : "RKFace",'
+ ' "depth" : "4",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/recovery/RKFace/0000000000.lij",'
+ ' "size" : "2723"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/recovery/RKFaceGroup",'
+ ' "shortname" : "RKFaceGroup",'
+ ' "depth" : "4",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/recovery/RKFaceGroup/0000000000.lij",'
+ ' "size" : "204"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/recovery/RKFaceGroupFace",'
+ ' "shortname" : "RKFaceGroupFace",'
+ ' "depth" : "4",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/recovery/RKFaceGroupFace/0000000000.lij",'
+ ' "size" : "231"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/recovery/RKFacePrint",'
+ ' "shortname" : "RKFacePrint",'
+ ' "depth" : "4",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/recovery/RKFacePrint/0000000000.lij",'
+ ' "size" : "5912"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/recovery/RKFolder",'
+ ' "shortname" : "RKFolder",'
+ ' "depth" : "4",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/recovery/RKFolder/0000000000.lij",'
+ ' "size" : "2878"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/recovery/RKImageProxyState",'
+ ' "shortname" : "RKImageProxyState",'
+ ' "depth" : "4",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/recovery/RKImageProxyState/0000000000.lij",'
+ ' "size" : "6608"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/recovery/RKImportGroup",'
+ ' "shortname" : "RKImportGroup",'
+ ' "depth" : "4",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/recovery/RKImportGroup/0000000000.lij",'
+ ' "size" : "202"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/recovery/RKKeyword",'
+ ' "shortname" : "RKKeyword",'
+ ' "depth" : "4",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/recovery/RKKeyword/0000000000.lij",'
+ ' "size" : "909"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/recovery/RKKeywordForVersion",'
+ ' "shortname" : "RKKeywordForVersion",'
+ ' "depth" : "4",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/recovery/RKKeywordForVersion/0000000000.lij",'
+ ' "size" : "236"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/recovery/RKMaster",'
+ ' "shortname" : "RKMaster",'
+ ' "depth" : "4",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/recovery/RKMaster/0000000000.lij",'
+ ' "size" : "1941"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/recovery/RKModelResource",'
+ ' "shortname" : "RKModelResource",'
+ ' "depth" : "4",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/recovery/RKModelResource/0000000000.lij",'
+ ' "size" : "2468"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/recovery/RKVersion",'
+ ' "shortname" : "RKVersion",'
+ ' "depth" : "4",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/resources/recovery/RKVersion/0000000000.lij",'
+ ' "size" : "7036"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ]'
+ ' }'
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/Thumbnails",'
+ ' "shortname" : "Thumbnails",'
+ ' "depth" : "2",'
+ ' "Files" : ['
+ ' ],'
+ ' "Folders" : ['
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/Thumbnails/2015",'
+ ' "shortname" : "2015",'
+ ' "depth" : "3",'
+ ' "Files" : ['
+ ' ],'
+ ' "Folders" : ['
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/Thumbnails/2015/11",'
+ ' "shortname" : "11",'
+ ' "depth" : "4",'
+ ' "Files" : ['
+ ' ],'
+ ' "Folders" : ['
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/Thumbnails/2015/11/08",'
+ ' "shortname" : "08",'
+ ' "depth" : "5",'
+ ' "Files" : ['
+ ' ],'
+ ' "Folders" : ['
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/Thumbnails/2015/11/08/20151108-154737",'
+ ' "shortname" : "20151108-154737",'
+ ' "depth" : "6",'
+ ' "Files" : ['
+ ' ],'
+ ' "Folders" : ['
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/Thumbnails/2015/11/08/20151108-154737/rIjZ4SLDRsexzPKOu0wonQ",'
+ ' "shortname" : "rIjZ4SLDRsexzPKOu0wonQ",'
+ ' "depth" : "7",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/Thumbnails/2015/11/08/20151108-154737/rIjZ4SLDRsexzPKOu0wonQ/thumb_Photo on 11-8-15 at 1.42 PM #2_1024.jpg",'
+ ' "size" : "129693"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/Thumbnails/2015/11/08/20151108-154737/sY0vA93GR2u7U1ITebQ7DQ",'
+ ' "shortname" : "sY0vA93GR2u7U1ITebQ7DQ",'
+ ' "depth" : "7",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/Thumbnails/2015/11/08/20151108-154737/sY0vA93GR2u7U1ITebQ7DQ/thumb_Photo on 11-8-15 at 1.42 PM #2_1024.jpg",'
+ ' "size" : "106748"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ]'
+ ' }'
+ ' ]'
+ ' }'
+ ' ]'
+ ' }'
+ ' ]'
+ ' }'
+ ' ,'
+ ' {'
+ ' "name" : "/Users/obzota/Files/Photos Library.photoslibrary/Thumbnails/Segments",'
+ ' "shortname" : "Segments",'
+ ' "depth" : "3",'
+ ' "Files" : ['
+ ' {'
+ ' "filename" : "/Users/obzota/Files/Photos Library.photoslibrary/Thumbnails/Segments/ThumbJPGSegment_0.data",'
+ ' "size" : "20480"'
+ ' }'
+ ' ],'
+ ' "Folders" : ['
+ ' ]'
+ ' }'
+ ' ]'
+ ' }'
+ ' ]'
+ ' }'
+ ' ]'
+ ' }'